make build work for all devices

diff --git a/TurnierInfo/generic/Makefile b/TurnierInfo/generic/Makefile
--- a/TurnierInfo/generic/Makefile
+++ b/TurnierInfo/generic/Makefile
@@ -6,7 +6,7 @@ apm821xx_nand_profiles := meraki_mr24 meraki_mx60 netgear_wndr4700
 ar71xx_generic_profiles := ALFAAP120C ALFAAP96 ALFANX ALL0258N ALL0305 ALL0315N AP121_8M ap121f ap90q ap91-5g AP96 archer-c25-v1 archer-c58-v1 archer-c59-v1 archer-c5-v1 archer-c60-v1 archer-c60-v2 archer-c7-v1 archer-c7-v2 archer-c7-v2-il archer-c7-v4 archer-c7-v5 c-55 cap324 CAP4200AG cf-e316n-v2 cf-e320n-v2 cf-e355ac-v1 cf-e355ac-v2 cf-e375ac cf-e380ac-v1 cf-e380ac-v2 cf-e385ac cf-e520n cf-e530n cpe210-220-v1 cpe210-v2 cpe510-520-v1 cpe830 cpe870 cr3000-nocloud dap-2695-a1 DGL5500A1 DHP1565A1 DIR825B1 DIR825C1 DIR835A1 dir-869-a1 dLAN_Hotspot dLAN_pro_1200_ac dLAN_pro_500_wp dr342 dragino2 e558-v2-8M e558-v2-16M e750a-v4-8M e750a-v4-16M eap120-v1 EAP300V2 EAP7660D el-mini EPG5000 ESR1750 ESR900 F9K1115V2 fritz300e fritz4020 gl-ar300 gl-usb150 hiwifi-hc6361 JA76PF2 JWAP003 jwap230 koala lan-turtle mc-mac1200r mr12 mr16 MR1750 MR600 MR900 mw4530r-v1 mynet-n600 mynet-n750 MYNETREXT MZKW04NU MZKW300NH n5q OM2P OM5P OM5PAC omy-g1 omy-x1 pqi-air-pen qihoo-c301 r36a rut900 rw2458n sr3200 t830 TEW673GRU TEW732BR TEW823DRU tl-mr6400-v1 tl-wdr3500-v1 tl-wdr3600-v1 tl-wdr4300-v1 tl-wdr4310-v1 tl-wdr4900-v2 tl-wdr6500-v2 tl-wdr7500-v3 tl-wr1043nd-v1 tl-wr1043nd-v2 tl-wr1043nd-v3 tl-wr1043nd-v4 tl-wr1043n-v5 tl-wr2543-v1 tl-wr710n-v2.1 tl-wr842n-v1 tl-wr842n-v2 tl-wr842n-v3 tl-wr902ac-v1 tl-wr942n-v1 TUBE2H16M TUBE2H8M ubnt-air-gateway-pro ubnt-air-gateway ubnt-airrouter ubnt-bullet-m ubnt-loco-m-xw ubnt-nano-m ubnt-nano-m-xw ubnt-rs ubnt-rspro ubnt-uap-pro ubnt-unifi ubnt-unifiac-lite ubnt-unifiac-mesh ubnt-unifiac-pro ubnt-unifi-outdoor ubnt-unifi-outdoor-plus wbs210-v1 wbs510-v1 wifi-pineapple-nano wlr8100 wndr3700 wndr3700v2 wndr3800 wndr3800ch WNR2200 WRT160NL WZR450HP2 WZR600DHP WZRHPAG300H WZRHPG300NH WZRHPG300NH2 WZRHPG450H xd3200 zbt-we1526 ZCN1523H28 ZCN1523H516
 ar71xx_mikrotik_profiles := nand-64m nand-large nand-large-ac rb-nor-flash-16M rb-nor-flash-16M-ac
 ar71xx_nand_profiles := c-60 domywifi-dw33d hiveap-121 mr18 NBG6716 R6100 rambutan wi2a-ac200i WNDR3700V4 WNDR4300V1 z1
-ar71xx_tiny_profiles := A02RBW300N DIR600A1 DIR601A1 DIR601B1 DIR615C1 DIR615E1 DIR615E4 DIR615I1 DIR615I3 EBR2310C1 FR54RTR N150R NBG_460N_550N_550NH REALWNR1000V2 REALWNR612V2 rnx-n360rt TEW632BRP TEW652BRP_FW TEW652BRP_RECOVERY TEW712BR tl-mr10u-v1 tl-mr11u-v1 tl-mr11u-v2 tl-mr12u-v1 tl-mr13u-v1 tl-mr3020-v1 tl-mr3040-v1 tl-mr3040-v2 tl-mr3220-v1 tl-mr3220-v2 tl-mr3420-v1 tl-mr3420-v2 tl-wa701nd-v1 tl-wa701nd-v2 tl-wa7210n-v2 tl-wa730re-v1 tl-wa750re-v1 tl-wa7510n-v1 tl-wa801nd-v1 tl-wa801nd-v2 tl-wa801nd-v3 tl-wa830re-v1 tl-wa830re-v2 tl-wa850re-v1 tl-wa850re-v2 tl-wa855re-v1 tl-wa860re-v1 tl-wa901nd-v1 tl-wa901nd-v2 tl-wa901nd-v3 tl-wa901nd-v4 tl-wa901nd-v5 tl-wdr3320-v2 tl-wr1041n-v2 tl-wr703n-v1 tl-wr710n-v2 tl-wr720n-v3 tl-wr720n-v4 tl-wr740n-v1 tl-wr740n-v3 tl-wr740n-v4 tl-wr740n-v5 tl-wr740n-v6 tl-wr741nd-v1 tl-wr741nd-v2 tl-wr741nd-v4 tl-wr741nd-v5 tl-wr743nd-v1 tl-wr743nd-v2 tl-wr802n-v1 tl-wr802n-v2 tl-wr840n-v2 tl-wr840n-v3 tl-wr841-v10 tl-wr841-v11 tl-wr841-v12 tl-wr841-v1.5tl-wr841-v3 tl-wr841-v5 tl-wr841-v7 tl-wr841-v8 tl-wr841-v9 tl-wr843nd-v1 tl-wr847n-v8 tl-wr940n-v4 tl-wr940n-v6 tl-wr941nd-v2 tl-wr941nd-v3 tl-wr941nd-v4 tl-wr941nd-v5 tl-wr941nd-v6 tl-wr941nd-v6-cn WHRG301N WHRHPG300N WHRHPGN WLAEAG300N WNR1000V2_VC WNR2000 WNR2000V3 WNR2000V4 WP543_4M WPE72_4M WPN824N
+ar71xx_tiny_profiles := A02RBW300N DIR600A1 DIR601A1 DIR601B1 DIR615C1 DIR615E1 DIR615E4 DIR615I1 DIR615I3 EBR2310C1 FR54RTR N150R NBG_460N_550N_550NH REALWNR1000V2 REALWNR612V2 rnx-n360rt TEW632BRP TEW652BRP_FW TEW652BRP_RECOVERY TEW712BR tl-mr10u-v1 tl-mr11u-v1 tl-mr11u-v2 tl-mr12u-v1 tl-mr13u-v1 tl-mr3020-v1 tl-mr3040-v1 tl-mr3040-v2 tl-mr3220-v1 tl-mr3220-v2 tl-mr3420-v1 tl-mr3420-v2 tl-wa701nd-v1 tl-wa701nd-v2 tl-wa7210n-v2 tl-wa730re-v1 tl-wa750re-v1 tl-wa7510n-v1 tl-wa801nd-v1 tl-wa801nd-v2 tl-wa801nd-v3 tl-wa830re-v1 tl-wa830re-v2 tl-wa850re-v1 tl-wa850re-v2 tl-wa855re-v1 tl-wa860re-v1 tl-wa901nd-v1 tl-wa901nd-v2 tl-wa901nd-v3 tl-wa901nd-v4 tl-wa901nd-v5 tl-wdr3320-v2 tl-wr1041n-v2 tl-wr703n-v1 tl-wr710n-v2 tl-wr720n-v3 tl-wr720n-v4 tl-wr740n-v1 tl-wr740n-v3 tl-wr740n-v4 tl-wr740n-v5 tl-wr740n-v6 tl-wr741nd-v1 tl-wr741nd-v2 tl-wr741nd-v4 tl-wr741nd-v5 tl-wr743nd-v1 tl-wr743nd-v2 tl-wr802n-v1 tl-wr802n-v2 tl-wr840n-v2 tl-wr840n-v3 tl-wr841-v10 tl-wr841-v11 tl-wr841-v12 tl-wr841-v1.5 tl-wr841-v3 tl-wr841-v5 tl-wr841-v7 tl-wr841-v8 tl-wr841-v9 tl-wr843nd-v1 tl-wr847n-v8 tl-wr940n-v4 tl-wr940n-v6 tl-wr941nd-v2 tl-wr941nd-v3 tl-wr941nd-v4 tl-wr941nd-v5 tl-wr941nd-v6 tl-wr941nd-v6-cn WHRG301N WHRHPG300N WHRHPGN WLAEAG300N WNR1000V2_VC WNR2000 WNR2000V3 WNR2000V4 WP543_4M WPE72_4M WPN824N
 
 bcm53xx_generic_profiles :=
 brcm2708_bcm2708_profiles := rpi
@@ -99,16 +99,17 @@ clean:
 
 .SUFFIXES:
 
-release/$(target)-$(subtarget): $(foreach profile,$($(target)_$(subtarget)_profiles),release/$(target)-$(subtarget)-$(profile)) release/$(target)_$(subtarget)_00EXCLUDED release
+release/$(target)-$(subtarget): $(foreach profile,$($(target)_$(subtarget)_profiles),release/$(target)-$(subtarget)-$(profile)) release/$(target)_$(subtarget)_00EXCLUDED | release
 	mkdir -p release/$(target)/$(subtarget)
 	cp -uR openwrt-imagebuilder-$(OPENWRT_VERSION)-$(target)-$(subtarget).Linux-x86_64/bin/targets/$(target)/$(subtarget)/* release/$(target)/$(subtarget) \
 	|| test "$($(target)_$(subtarget)_profiles)" = ""
 
-release/$(target)-$(subtarget)-%: openwrt-imagebuilder-$(OPENWRT_VERSION)-$(target)-$(subtarget).Linux-x86_64/ $(files) release
+release/$(target)-$(subtarget)-%: openwrt-imagebuilder-$(OPENWRT_VERSION)-$(target)-$(subtarget).Linux-x86_64/ $(files) | release
 	echo "Building Image for $(target) $(subtarget) $*"
-	make -C $< image PROFILE="$*" PACKAGES="vsftpd luci -ppp -ppp-mod-pppoe" EXTRA_IMAGE_NAME="TurnierInfo" FILES="../files/" >$@ 2>&1
+	{ make -C $< image PROFILE="$*" PACKAGES="vsftpd luci -ppp -ppp-mod-pppoe" EXTRA_IMAGE_NAME="TurnierInfo" FILES="../files/" >$@ 2>&1 ; } \
+	|| { mv --backup=numbered $@ release/00ERROR_$(target)-$(subtarget)-$* ; echo -e '\033[0;31m' "$(target) $(subtarget) $* FAILED" '\033[0m' ; }
 	
-release/$(target)_$(subtarget)_00EXCLUDED: openwrt-imagebuilder-$(OPENWRT_VERSION)-$(target)-$(subtarget).Linux-x86_64/ release
+release/$(target)_$(subtarget)_00EXCLUDED: openwrt-imagebuilder-$(OPENWRT_VERSION)-$(target)-$(subtarget).Linux-x86_64/ | release
 	make -C $< info | grep :$$ | tr -d : | sort > release/$(target)_$(subtarget)_00ALL
 	echo $($(target)_$(subtarget)_profiles)| tr ' ' \\n | sort > release/$(target)_$(subtarget)_00BUILT
 	diff release/$(target)_$(subtarget)_00ALL release/$(target)_$(subtarget)_00BUILT > $@ ; true
